<Project>
  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <InvariantGlobalization>true</InvariantGlobalization>
    <VersionPrefix>0.1.0</VersionPrefix>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Authors>ModsyncManager</Authors>
    <Product>ModsyncManager</Product>
    <Copyright>Copyright (C) 2026 UnholySaviorOmen</Copyright>
  </PropertyGroup>
</Project>