<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Modsync.Gui.Controls\Modsync.Gui.Controls.csproj" />
    <ProjectReference Include="..\Modsync.Gui.Shared\Modsync.Gui.Shared.csproj" />
    <ProjectReference Include="..\Modsync.Install\Modsync.Install.csproj" />
    <ProjectReference Include="..\Modsync.Pack\Modsync.Pack.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Pack\Views\PackConfigView.axaml.cs">
      <DependentUpon>PackConfigView.axaml</DependentUpon>
    </Compile>
  </ItemGroup>
</Project>