// SPDX-FileCopyrightText: 2026 UnholySaviorOmen
// SPDX-License-Identifier: GPL-3.0-only

using System.IO.Compression;
using System.Text;
using FluentAssertions;
using Modsync.Core.Archives;
using Modsync.Core.Archives.Extraction;
using Modsync.Core.Models.Hashing;
using Modsync.Core.Progress;
using Modsync.Pack;
using Modsync.Pack.Steps;
using Microsoft.Extensions.Logging.Abstractions;

namespace Modsync.Pack.Tests;

/// <summary>
/// Проверяет, что PackPipeline корректно репортит IProgress&lt;StepProgress&gt;.
///
/// Строит минимальный синтетический инстанс и проверяет:
///   - progress вызывается хотя бы раз;
///   - StepIndex идёт строго по возрастанию;
///   - StepIndex начинается с 1;
///   - TotalSteps одинаков во всех репортах;
///   - StepName непустой;
///   - последний StepName — "WriteManifest";
///   - если progress == null, pipeline всё равно работает.
/// </summary>
public class PackPipelineProgressTests : IDisposable
{
    private readonly string _tempDir;
    private readonly string _configPath;

    public PackPipelineProgressTests()
    {
        _tempDir = Path.Combine(
            Path.GetTempPath(), "modsyncmanager-pack-progress-" + Guid.NewGuid());
        Directory.CreateDirectory(_tempDir);
        _configPath = Path.Combine(_tempDir, "modsyncmanager-pack.json");

        BuildSyntheticInstance();
    }

    public void Dispose()
    {
        try { Directory.Delete(_tempDir, recursive: true); } catch { }
    }

    private void BuildSyntheticInstance()
    {
        var instanceDir = Path.Combine(_tempDir, "TestInstance");
        var mo2Dir = Path.Combine(instanceDir, "MO2");
        var downloadsDir = Path.Combine(mo2Dir, "downloads");
        var modsDir = Path.Combine(mo2Dir, "mods");
        var profileDir = Path.Combine(mo2Dir, "profiles", "Default");
        var stockGameDir = Path.Combine(instanceDir, "Stock Game");

        Directory.CreateDirectory(downloadsDir);
        Directory.CreateDirectory(modsDir);
        Directory.CreateDirectory(profileDir);
        Directory.CreateDirectory(stockGameDir);
        File.WriteAllBytes(
            Path.Combine(mo2Dir, "ModOrganizer.exe"), Array.Empty<byte>());

        // MO2-архив (zip с ModOrganizer.exe).
        var mo2ArchivePath = Path.Combine(downloadsDir, "Mod.Organizer-2.5.2.7z");
        using (var fs = File.Create(mo2ArchivePath))
        using (var zip = new ZipArchive(fs, ZipArchiveMode.Create))
        {
            var entry = zip.CreateEntry("ModOrganizer.exe");
            using var es = entry.Open();
            var bytes = Encoding.UTF8.GetBytes("fake mo2");
            es.Write(bytes, 0, bytes.Length);
        }

        var mo2Hash = XxHash64Value.FromFile(mo2ArchivePath);

        // Mod-архив.
        var modArchivePath = Path.Combine(downloadsDir, "testmod.7z");
        var fileContent = Encoding.UTF8.GetBytes("hello");
        using (var fs = File.Create(modArchivePath))
        using (var zip = new ZipArchive(fs, ZipArchiveMode.Create))
        {
            var entry = zip.CreateEntry("file.txt");
            using var es = entry.Open();
            es.Write(fileContent, 0, fileContent.Length);
        }

        File.WriteAllText(
            modArchivePath + ".meta",
            "[General]\r\ngameName=Skyrim\r\nmodID=1\r\nfileID=1\r\n");

        // Mod в инстансе.
        var modDir = Path.Combine(modsDir, "TestMod");
        Directory.CreateDirectory(modDir);
        File.WriteAllBytes(Path.Combine(modDir, "file.txt"), fileContent);

        // Профиль.
        File.WriteAllText(
            Path.Combine(profileDir, "modlist.txt"),
            "\uFEFF# This file was automatically generated by Mod Organizer.\r\n+TestMod\r\n");
        File.WriteAllText(
            Path.Combine(profileDir, "plugins.txt"),
            "\uFEFF# Plugins\r\n*Test.esp\r\n");
        File.WriteAllText(
            Path.Combine(profileDir, "loadorder.txt"),
            "\uFEFF# Loadorder\r\nSkyrim.esm\r\nTest.esp\r\n");

        // modsyncmanager-pack.json.
        var configJson = $$"""
        {
          "meta": {
            "name": "Progress Test Pack",
            "version": "1.0.0",
            "author": "tester",
            "game": "skyrimspecialedition",
            "gameVersion": "1.6.1170"
          },
          "instance": { "path": "TestInstance" },
          "mo2": {
            "version": "2.5.2",
            "profile": "Default",
            "archive": "Mod.Organizer-2.5.2.7z",
            "source": {
              "type": "mirror",
              "url": "https://example.com/Mod.Organizer-2.5.2.7z",
              "hash": "{{mo2Hash}}"
            },
            "extensions": []
          },
          "stockGame": { "extras": [] },
          "archiveSources": []
        }
        """;
        File.WriteAllText(_configPath, configJson);
    }

    private static PackPipeline BuildPipeline()
    {
        var hashCache = new FileHashCache();
        var extractor = new SevenZipExtractor(
            NullLogger<SevenZipExtractor>.Instance);

        return new PackPipeline(
            new ReadConfigStep(NullLogger<ReadConfigStep>.Instance),
            new ReadInstanceStep(NullLogger<ReadInstanceStep>.Instance),
            new IndexArchivesStep(
                hashCache, NullLogger<IndexArchivesStep>.Instance),
            new ScanModsStep(
                hashCache, NullLogger<ScanModsStep>.Instance),
            new ScanExtensionsStep(
                hashCache, NullLogger<ScanExtensionsStep>.Instance),
            new ScanExtrasStep(
                hashCache, NullLogger<ScanExtrasStep>.Instance),
            new MatchStep(
                NullLogger<MatchStep>.Instance),
            new MatchExtensionsStep(
                NullLogger<MatchExtensionsStep>.Instance),
            new MatchExtrasStep(
                NullLogger<MatchExtrasStep>.Instance),
            new BuildManifestStep(
                NullLogger<BuildManifestStep>.Instance),
            new ValidateManifestStep(
                NullLogger<ValidateManifestStep>.Instance),
            new WriteManifestStep(
                NullLogger<WriteManifestStep>.Instance),
            extractor,
            hashCache,
            NullLoggerFactory.Instance,
            NullLogger<PackPipeline>.Instance);
    }

    private static ParallelOptions ParallelOptions()
        => new() { MaxDegreeOfParallelism = 1 };

    /// <summary>
    /// Синхронный IProgress, копит репорты в список.
    /// </summary>
    private sealed class ListProgress : IProgress<StepProgress>
    {
        public List<StepProgress> Reports { get; } = new();
        public void Report(StepProgress value) => Reports.Add(value);
    }

    [Fact]
    public async Task Execute_WithProgress_ReportsAllSteps()
    {
        var pipeline = BuildPipeline();
        var progress = new ListProgress();

        var input = PackInputFactory.Create(_configPath, ParallelOptions());
        await pipeline.ExecuteAsync(input, CancellationToken.None, progress);

        // Должно быть 14 репортов — по одному на каждый StepName.
        progress.Reports.Should().HaveCount(14);

        // StepIndex идёт 1..14.
        progress.Reports.Select(r => r.StepIndex)
            .Should().Equal(Enumerable.Range(1, 14));

        // TotalSteps везде одинаковый.
        progress.Reports.Select(r => r.TotalSteps)
            .Should().AllBeEquivalentTo(14);

        // StepName непустой.
        progress.Reports.Select(r => r.StepName)
            .Should().NotContainNulls()
            .And.OnlyContain(s => !string.IsNullOrWhiteSpace(s));

        // Первый и последний — стабильные имена.
        progress.Reports[0].StepName.Should().Be("ReadConfig");
        progress.Reports[^1].StepName.Should().Be("WriteManifest");
    }

    [Fact]
    public async Task Execute_WithoutProgress_StillWorks()
    {
        var pipeline = BuildPipeline();

        // Третий аргумент — progress = null по умолчанию.
        var input = PackInputFactory.Create(_configPath, ParallelOptions());
        var result = await pipeline.ExecuteAsync(input, CancellationToken.None);

        result.Manifest.Meta.Name.Should().Be("Progress Test Pack");
        result.ManifestPath.Should().NotBeNullOrEmpty();
    }
}
