// SPDX-FileCopyrightText: 2026 UnholySaviorOmen
// SPDX-License-Identifier: GPL-3.0-only

using System.IO.Compression;
using System.Text;
using Modsync.Core.Archives;
using Modsync.Core.Archives.Extraction;
using Modsync.Core.Models.Hashing;
using Modsync.Core.Models.Manifest;
using Modsync.Core.Models.Manifest.Directives;
using Modsync.Pack.Steps;
using FluentAssertions;
using Microsoft.Extensions.Logging.Abstractions;

namespace Modsync.Pack.Tests;

/// <summary>
/// End-to-end тест пайплайна packer-а на синтетическом инстансе.
/// </summary>
public class PackPipelineIntegrationTests : IDisposable
{
    private readonly string _tempDir;
    private readonly string _configPath;

    public PackPipelineIntegrationTests()
    {
        _tempDir = Path.Combine(
            Path.GetTempPath(), "modsyncmanager-integ-" + Guid.NewGuid());
        Directory.CreateDirectory(_tempDir);
        _configPath = Path.Combine(_tempDir, "modsyncmanager-pack.json");

        BuildSyntheticInstance();
    }

    public void Dispose()
    {
        try { Directory.Delete(_tempDir, recursive: true); } catch { }
    }

    private void BuildSyntheticInstance()
    {
        var instanceDir = Path.Combine(_tempDir, "TestInstance");
        var mo2Dir = Path.Combine(instanceDir, "MO2");
        var downloadsDir = Path.Combine(mo2Dir, "downloads");
        var modsDir = Path.Combine(mo2Dir, "mods");
        var profileDir = Path.Combine(mo2Dir, "profiles", "Default");
        var stockGameDir = Path.Combine(instanceDir, "Stock Game");

        Directory.CreateDirectory(downloadsDir);
        Directory.CreateDirectory(modsDir);
        Directory.CreateDirectory(profileDir);
        Directory.CreateDirectory(stockGameDir);
        File.WriteAllBytes(Path.Combine(mo2Dir, "ModOrganizer.exe"), Array.Empty<byte>());

        var mo2ArchivePath = Path.Combine(downloadsDir, "Mod.Organizer-2.5.2.7z");
        using (var fs = File.Create(mo2ArchivePath))
        using (var zip = new ZipArchive(fs, ZipArchiveMode.Create))
        {
            var entry = zip.CreateEntry("ModOrganizer.exe");
            using var es = entry.Open();
            var bytes = Encoding.UTF8.GetBytes("fake mo2");
            es.Write(bytes, 0, bytes.Length);
        }

        var mo2Hash = XxHash64Value.FromFile(mo2ArchivePath);

        var fileContent = Encoding.UTF8.GetBytes("hello from mod");
        var zipPath = Path.Combine(downloadsDir, "testmod.7z");
        using (var fs = File.Create(zipPath))
        using (var zip = new ZipArchive(fs, ZipArchiveMode.Create))
        {
            var entry = zip.CreateEntry("some/file.txt");
            using var entryStream = entry.Open();
            entryStream.Write(fileContent, 0, fileContent.Length);
        }

        File.WriteAllText(
            zipPath + ".meta",
            "[General]\r\ngameName=Skyrim\r\nmodID=1\r\nfileID=1\r\n");

        var modDir = Path.Combine(modsDir, "TestMod");
        Directory.CreateDirectory(Path.Combine(modDir, "some"));
        File.WriteAllBytes(Path.Combine(modDir, "some", "file.txt"), fileContent);

        File.WriteAllText(
            Path.Combine(modDir, "meta.ini"),
            "[General]\r\n" +
            "gameName=Skyrim Special Edition\r\n" +
            "gameID=skyrimspecialedition\r\n" +
            "modID=1\r\n" +
            "fileID=1\r\n" +
            "version=1.0.0\r\n" +
            "notes=integration test note\r\n" +
            "\r\n" +
            "[installedFiles]\r\n" +
            "1\\some\\file.txt=DEADBEEF\r\n");

        File.WriteAllText(
            Path.Combine(profileDir, "modlist.txt"),
            "\uFEFF# This file was automatically generated by Mod Organizer.\r\n+TestMod\r\n");
        File.WriteAllText(
            Path.Combine(profileDir, "plugins.txt"),
            "\uFEFF# Plugins\r\n*Test.esp\r\n");
        File.WriteAllText(
            Path.Combine(profileDir, "loadorder.txt"),
            "\uFEFF# Loadorder\r\nSkyrim.esm\r\nTest.esp\r\n");

        var configJson = $$"""
        {
          "meta": {
            "name": "Test Pack",
            "version": "1.0.0",
            "author": "tester",
            "game": "skyrimspecialedition",
            "gameVersion": "1.6.1170"
          },
          "instance": {
            "path": "TestInstance"
          },
          "mo2": {
            "version": "2.5.2",
            "profile": "Default",
            "archive": "Mod.Organizer-2.5.2.7z",
            "source": {
              "type": "mirror",
              "url": "https://example.com/Mod.Organizer-2.5.2.7z",
              "hash": "{{mo2Hash}}"
            },
            "extensions": []
          },
          "stockGame": {
            "extras": []
          },
          "archiveSources": []
        }
        """;
        File.WriteAllText(_configPath, configJson);
    }

    private static PackPipeline BuildPipeline()
    {
        var hashCache = new FileHashCache();
        var extractor = new SevenZipExtractor(
            NullLogger<SevenZipExtractor>.Instance);

        var loggerFactory = NullLoggerFactory.Instance;

        return new PackPipeline(
            new ReadConfigStep(NullLogger<ReadConfigStep>.Instance),
            new ReadInstanceStep(NullLogger<ReadInstanceStep>.Instance),
            new IndexArchivesStep(
                hashCache, NullLogger<IndexArchivesStep>.Instance),
            new ScanModsStep(
                hashCache, NullLogger<ScanModsStep>.Instance),
            new ScanExtensionsStep(
                hashCache, NullLogger<ScanExtensionsStep>.Instance),
            new ScanExtrasStep(
                hashCache, NullLogger<ScanExtrasStep>.Instance),
            new MatchStep(
                NullLogger<MatchStep>.Instance),
            new MatchExtensionsStep(
                NullLogger<MatchExtensionsStep>.Instance),
            new MatchExtrasStep(
                NullLogger<MatchExtrasStep>.Instance),
            new BuildManifestStep(
                NullLogger<BuildManifestStep>.Instance),
            new ValidateManifestStep(
                NullLogger<ValidateManifestStep>.Instance),
            new WriteManifestStep(
                NullLogger<WriteManifestStep>.Instance),
            extractor,
            hashCache,
            loggerFactory,
            NullLogger<PackPipeline>.Instance);
    }

    private static ParallelOptions ParallelOptions()
        => new() { MaxDegreeOfParallelism = 1 };

    [Fact]
    public async Task FullPipeline_ProducesValidManifest()
    {
        var pipeline = BuildPipeline();

        var input = PackInputFactory.Create(_configPath, ParallelOptions());
        var result = await pipeline.ExecuteAsync(input, CancellationToken.None);

        result.Manifest.SchemaVersion.Should().Be("1.0.0");
        result.Manifest.Meta.Name.Should().Be("Test Pack");
        result.Manifest.Meta.Game.Should().Be("skyrimspecialedition");

        result.Manifest.Mods.Should().HaveCount(1);
        var mod = result.Manifest.Mods[0];
        mod.Name.Should().Be("TestMod");
        mod.Enabled.Should().BeTrue();
        mod.Order.Should().Be(0);
        mod.Meta.Should().NotBeNull();
        mod.Meta!.ModId.Should().Be(1);
        mod.Meta!.Version.Should().Be("1.0.0");
        mod.Meta!.Notes.Should().Be("integration test note");

        mod.Directives.Should().HaveCount(1);
        var directive = mod.Directives[0]
            .Should().BeOfType<FromArchiveDirective>().Subject;
        directive.Archive.Should().Be("nexus_skyrimspecialedition_1_1");
        directive.Source.Should().Be("some/file.txt");
        directive.Destination.Should().Be("some/file.txt");

        result.Manifest.Archives.Should().HaveCount(1);
        result.Manifest.Archives[0].Id.Should().Be("nexus_skyrimspecialedition_1_1");

        result.Manifest.Plugins.Should().HaveCount(1);
        result.Manifest.Plugins[0].Name.Should().Be("Test.esp");

        result.Manifest.Loadorder.Should().Equal("Skyrim.esm", "Test.esp");

        result.Manifest.Mo2.Archive.Id.Should().Be("local_mod-organizer-2-5-2");
        result.Manifest.Mo2.Archive.Name.Should().Be("Mod.Organizer-2.5.2.7z");
        result.Manifest.Mo2.Archive.Size.Should().BeGreaterThan(0);
        result.Manifest.Mo2.Archive.Sources.Should().HaveCount(1);
        result.Manifest.Mo2.Archive.Sources[0].Should().BeOfType<
            Modsync.Core.Models.Manifest.Sources.MirrorSourceRef>();

        result.Manifest.Mo2.Profile.Should().Be("Default");
    }

    [Fact]
    public async Task FullPipeline_WritesManifestToModsyncOutput()
    {
        var pipeline = BuildPipeline();

        var input = PackInputFactory.Create(_configPath, ParallelOptions());
        var result = await pipeline.ExecuteAsync(input, CancellationToken.None);

        var expectedPath = Path.Combine(
            _tempDir, "TestInstance", "__ModsyncManager_Output", "modlist.json");

        result.ManifestPath.Should().Be(expectedPath);
        File.Exists(expectedPath).Should().BeTrue();

        var json = File.ReadAllText(expectedPath);
        json.Should().Contain("\"schemaVersion\": \"1.0.0\"");
        json.Should().Contain("\"name\": \"TestMod\"");
        json.Should().Contain("\"name\": \"Test Pack\"");
    }

    [Fact]
    public async Task FullPipeline_ManifestDeserializesBack()
    {
        var pipeline = BuildPipeline();

        var input = PackInputFactory.Create(_configPath, ParallelOptions());
        var result = await pipeline.ExecuteAsync(input, CancellationToken.None);

        var json = File.ReadAllText(result.ManifestPath);
        var back = ManifestJson.Deserialize(json);

        back.Meta.Name.Should().Be("Test Pack");
        back.Mods.Should().HaveCount(1);
        back.Mods[0].Name.Should().Be("TestMod");
        back.Mods[0].Meta.Should().NotBeNull();
        back.Mods[0].Meta!.ModId.Should().Be(1);
        back.Mods[0].Directives.Should().HaveCount(1);
        back.Mods[0].Directives[0].Should().BeOfType<FromArchiveDirective>();
    }

    [Fact]
    public async Task FullPipeline_NoUnmatchedFiles()
    {
        var pipeline = BuildPipeline();

        var input = PackInputFactory.Create(_configPath, ParallelOptions());
        var result = await pipeline.ExecuteAsync(input, CancellationToken.None);

        result.Match.Unmatched.Should().BeEmpty();
        result.Match.ModMetas.Should().HaveCount(1);
        result.Match.ModMetas.Should().ContainKey("TestMod");
    }
}
