// SPDX-FileCopyrightText: 2026 UnholySaviorOmen
// SPDX-License-Identifier: GPL-3.0-only

using Modsync.Core.Models.Hashing;
using Modsync.Core.Models.Manifest.Sources;
using Modsync.Core.Models.Pack;
using Modsync.Pack.Steps;
using FluentAssertions;
using Microsoft.Extensions.Logging.Abstractions;

namespace Modsync.Pack.Tests;

public class ReadInstanceStepTests : IDisposable
{
    private readonly string _tempDir;
    private readonly string _instanceDir;
    private readonly string _mo2Dir;
    private readonly string _profilesDir;
    private readonly string _profileDir;
    private readonly ReadInstanceStep _step;

    public ReadInstanceStepTests()
    {
        _tempDir = Path.Combine(Path.GetTempPath(), "modsyncmanager-ri-" + Guid.NewGuid());
        _instanceDir = Path.Combine(_tempDir, "MyInstance");
        _mo2Dir = Path.Combine(_instanceDir, "MO2");
        _profilesDir = Path.Combine(_mo2Dir, "profiles");
        _profileDir = Path.Combine(_profilesDir, "Default");

        Directory.CreateDirectory(_mo2Dir);
        Directory.CreateDirectory(Path.Combine(_mo2Dir, "downloads"));
        Directory.CreateDirectory(Path.Combine(_mo2Dir, "mods"));
        Directory.CreateDirectory(_profileDir);
        Directory.CreateDirectory(Path.Combine(_instanceDir, "Stock Game"));

        File.WriteAllText(
            Path.Combine(_profileDir, "modlist.txt"),
            "\uFEFF# This file was automatically generated by Mod Organizer.\r\n+SkyUI\r\n-Requiem\r\n");

        File.WriteAllText(
            Path.Combine(_profileDir, "plugins.txt"),
            "\uFEFF# This file is used by Skyrim to keep track of your downloaded content.\r\n*Skyrim.esm\r\n*SkyUI.esp\r\n");

        File.WriteAllText(
            Path.Combine(_profileDir, "loadorder.txt"),
            "\uFEFF# This file was automatically generated by Mod Organizer.\r\nSkyrim.esm\r\nUpdate.esm\r\nSkyUI.esp\r\n");

        _step = new ReadInstanceStep(NullLogger<ReadInstanceStep>.Instance);
    }

    public void Dispose()
    {
        try { Directory.Delete(_tempDir, recursive: true); } catch { }
    }

    private static PackConfig MakeConfig(string instancePath = "MyInstance", string profile = "Default") => new()
    {
        Meta = new PackMeta
        {
            Name = "Test",
            Version = "1.0.0",
            Author = "a",
            Game = "skyrimspecialedition",
            GameVersion = "1.6.1170",
        },
        Instance = new PackInstance { Path = instancePath },
        Mo2 = new PackMo2
        {
            Version = "2.5.2",
            Profile = profile,
            Archive = "x.7z",
            Source = new MirrorSourceRef
            {
                Url = "https://example.com/x.7z",
                Hash = new XxHash64Value(0xabc),
            },
            Extensions = Array.Empty<string>(),
        },
        StockGame = new PackStockGame { Extras = Array.Empty<string>() },
        ArchiveSources = Array.Empty<PackArchiveSource>(),
    };

    private ReadInstanceStep.Input MakeInput(PackConfig? config = null) => new()
    {
        ConfigPath = Path.Combine(_tempDir, "modsyncmanager-pack.json"),
        Config = config ?? MakeConfig(),
    };

    [Fact]
    public async Task Execute_ValidInstance_ReturnsSnapshot()
    {
        var snapshot = await _step.ExecuteAsync(MakeInput(), CancellationToken.None);

        snapshot.InstancePath.Should().Be(_instanceDir);
        snapshot.Mo2Path.Should().Be(_mo2Dir);
        snapshot.DownloadsPath.Should().Be(Path.Combine(_mo2Dir, "downloads"));
        snapshot.ModsPath.Should().Be(Path.Combine(_mo2Dir, "mods"));
        snapshot.ProfilesPath.Should().Be(_profilesDir);
        snapshot.StockGamePath.Should().Be(Path.Combine(_instanceDir, "Stock Game"));

        snapshot.Modlist.Entries.Should().HaveCount(2);
        snapshot.Modlist.Entries[0].Name.Should().Be("SkyUI");
        snapshot.Modlist.Entries[0].Enabled.Should().BeTrue();
        snapshot.Modlist.Entries[1].Name.Should().Be("Requiem");
        snapshot.Modlist.Entries[1].Enabled.Should().BeFalse();

        snapshot.Plugins.Entries.Should().HaveCount(2);
        snapshot.Loadorder.Plugins.Should().Equal("Skyrim.esm", "Update.esm", "SkyUI.esp");
    }

    [Fact]
    public async Task Execute_MissingInstance_Throws()
    {
        var act = async () => await _step.ExecuteAsync(
            MakeInput(MakeConfig(instancePath: "MissingInstance")),
            CancellationToken.None);

        await act.Should().ThrowAsync<DirectoryNotFoundException>()
            .WithMessage("*Instance directory not found*");
    }

    [Fact]
    public async Task Execute_MissingProfile_Throws()
    {
        var act = async () => await _step.ExecuteAsync(
            MakeInput(MakeConfig(profile: "MissingProfile")),
            CancellationToken.None);

        await act.Should().ThrowAsync<DirectoryNotFoundException>()
            .WithMessage("*Profile not found*");
    }

    [Fact]
    public async Task Execute_MissingDownloads_Throws()
    {
        Directory.Delete(Path.Combine(_mo2Dir, "downloads"));

        var act = async () => await _step.ExecuteAsync(MakeInput(), CancellationToken.None);
        await act.Should().ThrowAsync<DirectoryNotFoundException>()
            .WithMessage("*downloads*");
    }

    [Fact]
    public async Task Execute_MissingMods_Throws()
    {
        Directory.Delete(Path.Combine(_mo2Dir, "mods"));

        var act = async () => await _step.ExecuteAsync(MakeInput(), CancellationToken.None);
        await act.Should().ThrowAsync<DirectoryNotFoundException>()
            .WithMessage("*mods*");
    }

    [Fact]
    public async Task Execute_MissingModlistFile_Throws()
    {
        File.Delete(Path.Combine(_profileDir, "modlist.txt"));

        var act = async () => await _step.ExecuteAsync(MakeInput(), CancellationToken.None);
        await act.Should().ThrowAsync<FileNotFoundException>();
    }
}
