using FluentAssertions;
using Modsync.Platform.MO2.Readers;

namespace Modsync.Platform.MO2.Tests;

public class LoadorderReaderTests
{
    [Fact]
    public void Parse_ReturnsPluginsInOrder()
    {
        var lines = new[]
        {
            "# This file was automatically generated by Mod Organizer.",
            "Skyrim.esm",
            "Update.esm",
            "Dawnguard.esm",
        };

        var file = LoadorderReader.Parse(lines);

        file.Plugins.Should().Equal("Skyrim.esm", "Update.esm", "Dawnguard.esm");
    }

    [Fact]
    public void Parse_HandlesBomInHeader()
    {
        var lines = new[]
        {
            "\uFEFF# This file was automatically generated by Mod Organizer.",
            "Skyrim.esm",
        };

        var file = LoadorderReader.Parse(lines);
        file.Plugins.Should().Equal("Skyrim.esm");
    }

    [Fact]
    public void Parse_RealWorldSample_PreservesCaseAndOrder()
    {
        // Отрывок из реального loadorder.txt
        var lines = new[]
        {
            "# This file was automatically generated by Mod Organizer.",
            "Skyrim.esm",
            "Update.esm",
            "Dawnguard.esm",
            "HearthFires.esm",
            "Dragonborn.esm",
            "ccasvsse001-almsivi.esm",
            "ccbgssse001-fish.esm",
            "_ResourcePack.esl",
            "unofficial skyrim special edition patch.esp",
        };

        var file = LoadorderReader.Parse(lines);

        file.Plugins.Should().HaveCount(9);
        file.Plugins[0].Should().Be("Skyrim.esm");
        file.Plugins[8].Should().Be("unofficial skyrim special edition patch.esp");
    }
}
