using FluentAssertions;
using Modsync.Core.Models.Mo2;
using Modsync.Platform.MO2.Readers;

namespace Modsync.Platform.MO2.Tests;

public class ModlistReaderTests
{
    [Fact]
    public void Parse_SimpleFile_ReturnsEntries()
    {
        var lines = new[]
        {
            "+SkyUI",
            "-SomeDisabledMod",
            "+Requiem",
        };

        var file = ModlistReader.Parse(lines);

        file.Entries.Should().HaveCount(3);
        file.Entries[0].Should().Be(new ModlistEntry("SkyUI", true));
        file.Entries[1].Should().Be(new ModlistEntry("SomeDisabledMod", false));
        file.Entries[2].Should().Be(new ModlistEntry("Requiem", true));
    }

    [Fact]
    public void Parse_WithBomAndComment_SkipsHeader()
    {
        var lines = new[]
        {
            "\uFEFF# This file was automatically generated by Mod Organizer.",
            "+SkyUI",
        };

        var file = ModlistReader.Parse(lines);

        file.Entries.Should().HaveCount(1);
        file.Entries[0].Name.Should().Be("SkyUI");
    }

    [Fact]
    public void Parse_Separators_AreJustDisabledMods()
    {
        var lines = new[]
        {
            "+SkyUI",
            "-# \U0001F4C2 Мои моды_separator",
            "+Requiem",
        };

        var file = ModlistReader.Parse(lines);

        file.Entries.Should().HaveCount(3);
        file.Entries[1].Name.Should().Be("# \U0001F4C2 Мои моды_separator");
        file.Entries[1].Enabled.Should().BeFalse();
    }

    [Fact]
    public void Parse_SkipsEmptyLines()
    {
        var lines = new[]
        {
            "+SkyUI",
            "",
            "   ",
            "+Requiem",
        };

        var file = ModlistReader.Parse(lines);
        file.Entries.Should().HaveCount(2);
    }

    [Fact]
    public void Parse_NamesWithSpacesAndSymbols_Preserved()
    {
        var lines = new[]
        {
            "+NAT Effect 11",
            "+[18+] - OStim Standalone",
            "+--- Modex",
            "+[Map] - Flat World Map Framework (FWMF)",
        };

        var file = ModlistReader.Parse(lines);

        file.Entries.Should().HaveCount(4);
        file.Entries[0].Name.Should().Be("NAT Effect 11");
        file.Entries[1].Name.Should().Be("[18+] - OStim Standalone");
        file.Entries[2].Name.Should().Be("--- Modex");
        file.Entries[3].Name.Should().Be("[Map] - Flat World Map Framework (FWMF)");
    }
}
