// SPDX-FileCopyrightText: 2026 UnholySaviorOmen
// SPDX-License-Identifier: GPL-3.0-only

using System.Text;
using Modsync.Core.Models.Mo2;

namespace Modsync.Platform.MO2.Writers;

public static class LoadorderWriter
{
    private const string Header =
        "# This file was automatically generated by Mod Organizer.";

    public static void WriteFile(string path, LoadorderFile file)
    {
        var content = Serialize(file);
        File.WriteAllText(
            path, content, new UTF8Encoding(encoderShouldEmitUTF8Identifier: true));
    }

    /// <summary>
    /// Сериализует содержимое loadorder.txt в строку (для verify).
    /// </summary>
    public static string Serialize(LoadorderFile file)
    {
        var sb = new StringBuilder();
        sb.Append(Header).Append("\r\n");
        foreach (var plugin in file.Plugins)
        {
            sb.Append(plugin).Append("\r\n");
        }

        return sb.ToString();
    }
}
