// SPDX-FileCopyrightText: 2026 UnholySaviorOmen
// SPDX-License-Identifier: GPL-3.0-only

using System.Text;
using Modsync.Core.Models.Mo2;

namespace Modsync.Platform.MO2.Writers;

/// <summary>
/// Запись modlist.txt.
/// MO2 пишет файл в UTF-8 с BOM, переводы строк CRLF.
/// Порядок строк — как в IEnumerable (не переворачиваем).
/// </summary>
public static class ModlistWriter
{
    private const string Header =
        "# This file was automatically generated by Mod Organizer.";

    public static void WriteFile(string path, ModlistFile file)
    {
        var content = Serialize(file);
        File.WriteAllText(
            path, content, new UTF8Encoding(encoderShouldEmitUTF8Identifier: true));
    }

    /// <summary>
    /// Сериализует содержимое modlist.txt в строку.
    /// Verify использует этот метод, чтобы регенерировать файл в память
    /// и сравнить с фактическим содержимым — без записи на диск.
    /// </summary>
    public static string Serialize(ModlistFile file)
    {
        var sb = new StringBuilder();
        sb.Append(Header).Append("\r\n");
        foreach (var entry in file.Entries)
        {
            sb.Append(entry.Enabled ? '+' : '-');
            sb.Append(entry.Name);
            sb.Append("\r\n");
        }

        return sb.ToString();
    }
}
